# Generated by Django 6.0.1 on 2026-01-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='license_img',
        ),
        migrations.AddField(
            model_name='driver',
            name='cdl_file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/cdl/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_w9_file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/w9/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='ifta_sticker_file',
            field=models.FileField(blank=True, null=True, upload_to='trucks/ifta/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='insurance_file',
            field=models.FileField(blank=True, null=True, upload_to='trucks/insurance/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='medical_card_file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/medical/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='registration_file',
            field=models.FileField(blank=True, null=True, upload_to='trucks/registration/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='load',
            name='bol_file',
            field=models.FileField(blank=True, null=True, upload_to='loads/bol/'),
        ),
        migrations.AddField(
            model_name='load',
            name='pod_file',
            field=models.FileField(blank=True, null=True, upload_to='loads/pod/'),
        ),
        migrations.AddField(
            model_name='load',
            name='rate_con_file',
            field=models.FileField(blank=True, null=True, upload_to='loads/ratecons/'),
        ),
    ]
