# Generated by Django 6.0.1 on 2026-01-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='broker_mc',
            field=models.CharField(default='000000', max_length=20),
        ),
        migrations.AddField(
            model_name='load',
            name='broker_name',
            field=models.CharField(default='TBD', max_length=200),
        ),
        migrations.AddField(
            model_name='load',
            name='load_ref',
            field=models.CharField(default='REF-001', max_length=50),
        ),
    ]
