# Generated by Django 6.0.1 on 2026-01-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_load_broker_mc_load_broker_name_load_load_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='load',
            name='rate_confirmation',
            field=models.FileField(blank=True, null=True, upload_to='rate_cons/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('ready', '🟢 Ready'), ('loaded', '🔴 Loaded'), ('home', '🟡 Home')], default='ready', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Dispatcher'), ('client', 'Truck Owner')], default='admin', max_length=10),
        ),
    ]
