# Generated by Django 6.0.1 on 2026-01-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_driver_license_img_driver_cdl_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='broker_mc',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='load',
            name='broker_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='load',
            name='miles',
            field=models.IntegerField(default=0),
        ),
    ]
