# Generated by Django 6.0.1 on 2026-01-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_phone_load_rate_confirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='authority_doc',
            field=models.FileField(blank=True, null=True, upload_to='company_docs/', verbose_name='My MC Authority'),
        ),
        migrations.AddField(
            model_name='company',
            name='insurance_doc',
            field=models.FileField(blank=True, null=True, upload_to='company_docs/', verbose_name='My Insurance Certificate'),
        ),
        migrations.AddField(
            model_name='company',
            name='w9_doc',
            field=models.FileField(blank=True, null=True, upload_to='company_docs/', verbose_name='My W-9'),
        ),
        migrations.AddField(
            model_name='driver',
            name='cdl',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/cdl/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='ifta_sticker',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/ifta/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='insurance_cert',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/insurance/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='mc_authority',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/authority/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='medical_card',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/medical/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='registration',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/registration/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='w9_form',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/w9/'),
        ),
        migrations.AddField(
            model_name='load',
            name='bill_of_lading',
            field=models.FileField(blank=True, null=True, upload_to='load_docs/bol/'),
        ),
        migrations.AddField(
            model_name='load',
            name='broker_agreement',
            field=models.FileField(blank=True, null=True, upload_to='load_docs/agreements/'),
        ),
        migrations.AddField(
            model_name='load',
            name='freight_photo',
            field=models.ImageField(blank=True, null=True, upload_to='load_docs/photos/'),
        ),
        migrations.AddField(
            model_name='load',
            name='lumper_receipt',
            field=models.FileField(blank=True, null=True, upload_to='load_docs/lumper/'),
        ),
        migrations.AddField(
            model_name='load',
            name='scale_ticket',
            field=models.FileField(blank=True, null=True, upload_to='load_docs/scale/'),
        ),
        migrations.AddField(
            model_name='load',
            name='temp_log',
            field=models.FileField(blank=True, null=True, upload_to='load_docs/temp/'),
        ),
        migrations.AlterField(
            model_name='load',
            name='rate_confirmation',
            field=models.FileField(blank=True, null=True, upload_to='load_docs/rate_cons/'),
        ),
    ]
