# Generated by Django 6.0.1 on 2026-01-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_authority_doc_company_insurance_doc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='mc_authority',
        ),
        migrations.RemoveField(
            model_name='load',
            name='broker_agreement',
        ),
        migrations.RemoveField(
            model_name='load',
            name='freight_photo',
        ),
        migrations.RemoveField(
            model_name='load',
            name='lumper_receipt',
        ),
        migrations.RemoveField(
            model_name='load',
            name='scale_ticket',
        ),
        migrations.RemoveField(
            model_name='load',
            name='temp_log',
        ),
        migrations.AddField(
            model_name='company',
            name='authority_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='driver_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Driver Pay (Cost)'),
        ),
        migrations.AddField(
            model_name='load',
            name='net_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='authority_doc',
            field=models.FileField(blank=True, null=True, upload_to='company_docs/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='insurance_doc',
            field=models.FileField(blank=True, null=True, upload_to='company_docs/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='w9_doc',
            field=models.FileField(blank=True, null=True, upload_to='company_docs/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='cdl',
            field=models.FileField(blank=True, null=True, upload_to='fleet_docs/driver/', verbose_name='CDL License'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='ifta_sticker',
            field=models.FileField(blank=True, null=True, upload_to='fleet_docs/truck/', verbose_name='IFTA Sticker'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='insurance_cert',
            field=models.FileField(blank=True, null=True, upload_to='fleet_docs/truck/', verbose_name='Truck Insurance (COI)'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='medical_card',
            field=models.FileField(blank=True, null=True, upload_to='fleet_docs/driver/', verbose_name='Medical Card'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='registration',
            field=models.FileField(blank=True, null=True, upload_to='fleet_docs/truck/', verbose_name='Truck Registration'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='w9_form',
            field=models.FileField(blank=True, null=True, upload_to='fleet_docs/driver/', verbose_name='W-9 Form'),
        ),
        migrations.AlterField(
            model_name='load',
            name='bill_of_lading',
            field=models.FileField(blank=True, null=True, upload_to='load_docs/'),
        ),
        migrations.AlterField(
            model_name='load',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gross Rate'),
        ),
        migrations.AlterField(
            model_name='load',
            name='rate_confirmation',
            field=models.FileField(blank=True, null=True, upload_to='load_docs/'),
        ),
    ]
