# Generated by Django 6.0.1 on 2026-01-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_driver_mc_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='dot_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='plan_type',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='truck_type',
            field=models.CharField(choices=[('dry_van', "Dry Van (53')"), ('reefer', 'Reefer'), ('flatbed', 'Flatbed'), ('stepdeck', 'Step Deck'), ('power_only', 'Power Only'), ('box_truck', "Box Truck (26')"), ('hotshot', 'Hotshot')], default='dry_van', max_length=20),
        ),
        migrations.AddField(
            model_name='load',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='cdl',
            field=models.FileField(blank=True, null=True, upload_to='fleet_docs/driver/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='ifta_sticker',
            field=models.FileField(blank=True, null=True, upload_to='fleet_docs/truck/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='insurance_cert',
            field=models.FileField(blank=True, null=True, upload_to='fleet_docs/truck/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='medical_card',
            field=models.FileField(blank=True, null=True, upload_to='fleet_docs/driver/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='registration',
            field=models.FileField(blank=True, null=True, upload_to='fleet_docs/truck/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('ready', '🟢 Ready'), ('loaded', '🔴 Loaded'), ('home', '🟡 Home'), ('shop', '🔧 Shop')], default='ready', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='w9_form',
            field=models.FileField(blank=True, null=True, upload_to='fleet_docs/driver/'),
        ),
        migrations.AlterField(
            model_name='load',
            name='driver_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='load',
            name='pickup_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='load',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
