# Generated by Django 6.0.1 on 2026-01-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_address_company_city_company_dot_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
