# Generated by Django 6.0.1 on 2026-01-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_payment_receipt_company_payment_submitted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='ifta_sticker',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='insurance_cert',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='w9_form',
        ),
        migrations.RemoveField(
            model_name='load',
            name='rpm',
        ),
        migrations.AlterField(
            model_name='driver',
            name='cdl',
            field=models.FileField(blank=True, null=True, upload_to='fleet_docs/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='medical_card',
            field=models.FileField(blank=True, null=True, upload_to='fleet_docs/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='registration',
            field=models.FileField(blank=True, null=True, upload_to='fleet_docs/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(default='ready', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='truck_type',
            field=models.CharField(choices=[('dry_van', "Dry Van (53')"), ('reefer', 'Reefer'), ('flatbed', 'Flatbed'), ('power_only', 'Power Only'), ('box_truck', 'Box Truck')], default='dry_van', max_length=20),
        ),
        migrations.AlterField(
            model_name='load',
            name='delivery_date',
            field=models.DateTimeField(default='2026-01-01 00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='load',
            name='load_ref',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='load',
            name='miles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='load',
            name='status',
            field=models.CharField(default='booked', max_length=20),
        ),
    ]
